# CI type:shell
# https://github.com/coolsnowwolf/lede
# CI ref:https://github.com/coolsnowwolf/lede/blob/master/.github/workflows/openwrt-ci.yml
# base
# ubuntu 16.04 x64 
# sudo apt-get update 
# sudo apt-get install build-essential asciidoc binutils 
# bzip2 gawk gettext git libncurses5-dev libz-dev patch 
# unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion 
# flex uglifyjs git-core gcc-multilib p7zip p7zip-full 
# msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils 
# upx libelf-dev autoconf automake libtool autopoint 
# device-tree-compiler
#
# git clone url
# /home/gitlab-runner/builds/b5d89257/0/shihuang/routerbuild
#
# 本CI目前暂时仅用于本服务器上自用，如需个性化使用，建议使用github的action功能！
#

stages:
  - r7800

job_base:
  stage: base
  tags: 
  - shell
  script:
    ## clean build
    #- cd /home/gitlab-runner/
    #- rm -R lede
    #- git clone https://github.com/coolsnowwolf/lede.git
    # update code
    - cd /home/gitlab-runner/lede
    - git pull
    ## remove feeds and tmp
    #- cd /home/gitlab-runner/lede
    #- rm -rf ./tmp
    #- rm -rf ./feeds
    ### 如果卡下载应该清除一下dl目录
    ## remove dl
    #- cd /home/gitlab-runner/lede
    #- rm -rf ./dl
    - ./scripts/feeds update -a
    - ./scripts/feeds install -a
    

job_r7800:
  stage: r7800
  tags: 
  - shell
  script: |
    cd /home/gitlab-runner/lede
    rm -f ./.config*
    touch ./.config
    
    echo 'Custom configure file'
    #
    # ========================固件定制部分========================
    # 
    # 编译r7800固件:
    cat >> .config <<EOF
    CONFIG_TARGET_ipq806x=y
    CONFIG_TARGET_ipq806x_DEVICE_netgear_r7800=y
    EOF
    # 常用LuCI插件选择:
    cat >> .config <<EOF
    CONFIG_PACKAGE_luci-app-ssr-plus=y
    CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
    CONFIG_PACKAGE_luci-app-guest-wifi=y
    CONFIG_PACKAGE_luci-i18n-guest-wifi-zh-cn=y
    CONFIG_PACKAGE_luci-app-accesscontrol=y
    CONFIG_PACKAGE_luci-app-ddns=y
    CONFIG_PACKAGE_luci-app-ipsec-vpnd=y
    CONFIG_PACKAGE_luci-app-pptp-server=y
    CONFIG_PACKAGE_luci-app-qbittorrent=y
    CONFIG_PACKAGE_luci-app-unblockmusic=y
    CONFIG_PACKAGE_luci-app-vlmcsd=y
    CONFIG_PACKAGE_luci-app-wol=y
    CONFIG_PACKAGE_luci-app-xlnetacc=y
    CONFIG_PACKAGE_luci-app-zerotier=y
    EOF
    # LuCI主题:
    cat >> .config <<EOF
    CONFIG_PACKAGE_luci-theme-argon=y
    CONFIG_PACKAGE_luci-theme-bootstrap=y
    CONFIG_PACKAGE_luci-theme-material=y
    EOF
    # 取消编译(不要删除被缩进的注释符号):
    cat >> .config <<EOF
    # CONFIG_PACKAGE_luci-app-shadowsocks-libev is not set
    # CONFIG_PACKAGE_luci-app-v2ray-server is not set
    EOF
    # 
    # ========================固件定制部分结束========================
    # 
    
    echo 'Generate configuration file'
    # 对比配置文件：
    cd /home/gitlab-runner/lede
    sed -i 's/^[ \t]*//g' ./.config
    make defconfig
    #- export FORCE_UNSAFE_CONFIGURE=1 && make -j4 V=s
    
    echo 'Make download'
    make download -j1
    echo 'Compile firmware'
    make -j1
    
    echo 'Assemble artifact'
    # build pass and save
    ## config
    cp /home/gitlab-runner/lede/.config /home/gitlab-runner/builds/b5d89257/0/shihuang/routerbuild/bin/.config
    ## netgear_r7800
    cp /home/gitlab-runner/lede/bin/targets/ipq806x/generic/openwrt-ipq806x-netgear_r7800-squashfs-factory.img /home/gitlab-runner/builds/b5d89257/0/shihuang/routerbuild/bin/`date   +%Y%m%d`-$CI_JOB_ID-openwrt-ipq806x-netgear_r7800-squashfs-factory.img
    cp /home/gitlab-runner/lede/bin/targets/ipq806x/generic/openwrt-ipq806x-netgear_r7800-squashfs-sysupgrade.bin /home/gitlab-runner/builds/b5d89257/0/shihuang/routerbuild/bin/`date   +%Y%m%d`-$CI_JOB_ID-openwrt-ipq806x-netgear_r7800-squashfs-sysupgrade.bin
    ## remove git file
    cd /home/gitlab-runner/builds/b5d89257/0/shihuang/routerbuild/bin
    rm .gitignore
  artifacts:
    name: "`date   +%Y%m%d`-$CI_JOB_ID-openwrt-router-r7800"
    #expire_in: 2 weeks
    paths:
      - /home/gitlab-runner/builds/b5d89257/0/shihuang/routerbuild/bin
  # disable artifact passing
  dependencies: []
